# Generated by Django 4.1.1 on 2022-09-27 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razdel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50, unique=True)),
                ('fname', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='razdel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='razdel_posts', to='blog.razdel'),
        ),
    ]
