# Generated by Django 4.1.1 on 2022-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_razdel_created_on_razdel_slug_razdel_update_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_id',
            field=models.UUIDField(default=0),
        ),
    ]
