# Generated by Django 4.1.1 on 2022-09-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_work_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='razdel',
        ),
        migrations.AddField(
            model_name='post',
            name='work',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_posts', to='blog.work'),
        ),
    ]
