# Generated by Django 4.1.1 on 2022-09-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_mcrblogposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='McrBlogPosts',
        ),
    ]
