# Generated by Django 4.1.1 on 2022-09-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_zakupki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakupki',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
