# Generated by Django 4.1.1 on 2022-09-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_zakupki_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zakupki',
        ),
    ]
