# Generated by Django 4.1.1 on 2022-09-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_zakupki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakupki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=2048)),
                ('price', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
