# Generated by Django 4.1.1 on 2022-10-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_zakupki'),
    ]

    operations = [
        migrations.AddField(
            model_name='razdel',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
