# Generated by Django 4.1.1 on 2022-10-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_razdel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razdel',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
