# Generated by Django 4.1.1 on 2022-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_razdel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razdel',
            name='icon',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
