# Generated by Django 4.1.1 on 2022-10-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='tech',
            field=models.BooleanField(default=False, verbose_name='Технические работы'),
        ),
    ]
