# Generated by Django 4.1.1 on 2022-10-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='work',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_files', to='blog.work'),
        ),
    ]
