# Generated by Django 4.1.1 on 2022-10-11 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0028_file_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.CreateModel(
            name='Normativ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normativs', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_normativ', to='blog.work')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_instruction', to='blog.work')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='FZayavki',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zayavki', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_zayavki', to='blog.work')),
            ],
            options={
                'verbose_name': 'Форма заявки',
                'verbose_name_plural': 'Формы заявок',
            },
        ),
    ]
