# Generated by Django 4.1.1 on 2022-10-12 05:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_file_options_normativ_instruction_fzayavki'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fzayavki',
            options={'ordering': ['-created_on'], 'verbose_name': 'Форма заявки', 'verbose_name_plural': 'Формы заявок'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['-created_on'], 'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_on'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='normativ',
            options={'ordering': ['-created_on'], 'verbose_name': 'Нормативный документ', 'verbose_name_plural': 'Нормативные документы'},
        ),
        migrations.AddField(
            model_name='file',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 12, 5, 21, 44, 771336, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fzayavki',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 12, 5, 21, 49, 545777, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fzayavki',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='normativ',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normativ',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
