# Generated by Django 4.1.1 on 2022-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_fzayavki_options_alter_instruction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentBdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=2048)),
                ('desc', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_on'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
